/* Shared WOD library — used by the WOD Finder (wods.html) and the WOD picker
 * on a WOD training day (workout.html). Add as many as you want.
 * Format: [name, format, equipment[], description, category]
 * category: "girl" | "hero" | "other"
 * Rx loads shown are the men's prescription — scale to you. */
window.WODS = [
  // ============ THE GIRLS (CrossFit benchmark) ============
  ["Fran","For Time",["Barbell","Pull-up bar"],"21-15-9: thrusters (95) + pull-ups. The classic sprint — go unbroken if you can.","girl"],
  ["Helen","RFT",["Kettlebell","Pull-up bar"],"3 rounds: 400 m run, 21 KB swings (53), 12 pull-ups.","girl"],
  ["Grace","For Time",["Barbell"],"30 clean & jerks for time (135).","girl"],
  ["Isabel","For Time",["Barbell"],"30 snatches for time (135).","girl"],
  ["Elizabeth","For Time",["Barbell","Bodyweight"],"21-15-9: power cleans (135) + ring dips.","girl"],
  ["Amanda","For Time",["Pull-up bar","Barbell"],"9-7-5: muscle-ups + squat snatches (135).","girl"],
  ["Cindy","AMRAP",["Pull-up bar","Bodyweight"],"20 min AMRAP: 5 pull-ups, 10 push-ups, 15 air squats.","girl"],
  ["Mary","AMRAP",["Bodyweight"],"20 min AMRAP: 5 HSPU, 10 pistols, 15 pull-ups (scale freely).","girl"],
  ["Annie","For Time",["Jump rope"],"50-40-30-20-10: double-unders + sit-ups.","girl"],
  ["Jackie","For Time",["Rower","Barbell","Pull-up bar"],"1000 m row, 50 thrusters (45), 30 pull-ups.","girl"],
  ["Diane","For Time",["Barbell"],"21-15-9: deadlift (225) + handstand push-ups (scale HSPU).","girl"],
  ["Karen","For Time",["Wall ball"],"150 wall balls (20) for time. Pace the sets.","girl"],
  ["Nancy","RFT",["Barbell"],"5 rounds: 400 m run + 15 overhead squats (95).","girl"],
  ["Barbara","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 pull-ups, 30 push-ups, 40 sit-ups, 50 squats — rest 3 min between rounds.","girl"],
  ["Angie","For Time",["Pull-up bar","Bodyweight"],"100 pull-ups, 100 push-ups, 100 sit-ups, 100 squats — finish each before moving on.","girl"],
  ["Chelsea","EMOM",["Pull-up bar","Bodyweight"],"EMOM 30 min: 5 pull-ups, 10 push-ups, 15 squats.","girl"],
  ["Eva","RFT",["Kettlebell","Pull-up bar"],"5 rounds: 800 m run, 30 KB swings (70), 30 pull-ups. A grinder.","girl"],
  ["Lynne","RFT",["Barbell","Pull-up bar"],"5 rounds, no time cap: bodyweight bench press (max reps) + max pull-ups. Rest as needed.","girl"],
  ["Nicole","AMRAP",["Pull-up bar"],"20 min AMRAP: 400 m run, then max pull-ups (note the number each round).","girl"],
  ["Linda","For Time",["Barbell"],"\"3 bars of death\" 10-9-8…1: deadlift (1.5x bw), bench press (bw), clean (0.75x bw).","girl"],
  ["Kelly","RFT",["Box","Wall ball"],"5 rounds: 400 m run, 30 box jumps (24), 30 wall balls (20).","girl"],
  ["Nasty Girls","RFT",["Bodyweight","Pull-up bar","Barbell"],"3 rounds: 50 squats, 7 muscle-ups, 10 hang power cleans (135).","girl"],
  ["Gwen","For Time",["Barbell"],"Clean & jerk 15-12-9, same load all sets, touch-and-go at floor, rest as needed. You pick the weight.","girl"],
  ["Maggie","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 handstand push-ups, 40 pull-ups, 60 alternating pistols.","girl"],
  ["Candy","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 pull-ups, 40 push-ups, 60 squats.","girl"],

  // ============ HERO WODs ============
  ["Murph","For Time",["Pull-up bar","Bodyweight"],"1 mi run, 100 pull-ups, 200 push-ups, 300 squats, 1 mi run. Vest optional. Partition the middle.","hero"],
  ["DT","RFT",["Barbell"],"5 rounds: 12 deadlifts, 9 hang power cleans, 6 push jerks (155).","hero"],
  ["The Chief","AMRAP",["Barbell","Bodyweight"],"5 cycles of 3 min AMRAP: 3 power cleans (135), 6 push-ups, 9 squats. 1 min rest between.","hero"],
  ["JT","For Time",["Bodyweight"],"21-15-9: handstand push-ups, ring dips, push-ups.","hero"],
  ["Randy","For Time",["Barbell"],"75 power snatches for time (75).","hero"],
  ["Chad","For Time",["Box"],"1000 box step-ups (20 in). Wear a ruck/vest (45) if able.","hero"],
  ["Glen","For Time",["Barbell","Pull-up bar"],"30 clean & jerks (135), 1 mi run, 10 rope climbs, 1 mi run, 100 burpees.","hero"],
  ["Holleyman","RFT",["Wall ball","Barbell"],"30 rounds: 5 wall balls (20), 3 HSPU, 1 power clean (225).","hero"],
  ["Wittman","RFT",["Kettlebell","Barbell","Box"],"7 rounds: 15 KB swings (53), 15 power cleans (95), 15 box jumps (24).","hero"],
  ["Daniel","For Time",["Pull-up bar","Barbell"],"50 pull-ups, 400 m run, 21 thrusters (95), 800 m run, 21 thrusters, 400 m run, 50 pull-ups.","hero"],
  ["Josh","For Time",["Barbell","Pull-up bar"],"21 OHS (95) + 42 pull-ups, 15 OHS + 30 pull-ups, 9 OHS + 18 pull-ups.","hero"],
  ["Roy","RFT",["Barbell","Box","Pull-up bar"],"5 rounds: 15 deadlifts (225), 20 box jumps (24), 25 pull-ups.","hero"],
  ["Ryan","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 7 muscle-ups, 21 burpees (chest to deck).","hero"],
  ["Nate","AMRAP",["Pull-up bar","Kettlebell"],"20 min AMRAP: 2 muscle-ups, 4 HSPU, 8 KB swings (70).","hero"],
  ["Tommy V","For Time",["Barbell"],"21 thrusters (115), 12 rope climbs, 15 thrusters, 9 rope climbs, 9 thrusters, 6 rope climbs.","hero"],
  ["Jason","For Time",["Bodyweight","Pull-up bar"],"100 squats, 5 muscle-ups, 75 squats, 10 MU, 50 squats, 15 MU, 25 squats, 20 MU.","hero"],
  ["Loredo","RFT",["Bodyweight"],"6 rounds: 24 squats, 24 push-ups, 24 walking lunges, 400 m run.","hero"],
  ["Bradshaw","RFT",["Barbell","Pull-up bar","Jump rope"],"10 rounds: 3 HSPU, 6 deadlifts (225), 12 pull-ups, 24 double-unders.","hero"],
  ["McGhee","AMRAP",["Barbell","Box"],"30 min AMRAP: 5 deadlifts (275), 13 push-ups, 9 box jumps (24).","hero"],
  ["The Seven","RFT",["Barbell","Pull-up bar","Kettlebell"],"7 rounds: 7 HSPU, 7 thrusters (135), 7 knees-to-elbow, 7 deadlifts (245), 7 burpees, 7 KB swings (70), 7 pull-ups.","hero"],
  ["Coe","RFT",["Barbell","Bodyweight"],"10 rounds: 10 thrusters (95), 10 ring push-ups.","hero"],
  ["Hammer","RFT",["Barbell","Pull-up bar"],"5 rounds: 5 power cleans (135), 10 front squats, 5 jerks, 20 pull-ups. Rest 90 s between.","hero"],
  ["Badger","RFT",["Barbell","Pull-up bar"],"3 rounds: 30 squat cleans (95), 30 pull-ups, 800 m run.","hero"],
  ["Joshie","RFT",["Dumbbells","Pull-up bar"],"3 rounds: 21 DB squat snatches right (40), 21 L-pull-ups, 21 DB squat snatches left, 21 L-pull-ups.","hero"],
  ["Danny","AMRAP",["Box","Barbell","Pull-up bar"],"20 min AMRAP: 30 box jumps (24), 20 push press (115), 30 pull-ups.","hero"],
  ["Hansen","RFT",["Kettlebell","Bodyweight"],"5 rounds: 30 KB swings (70), 30 burpees, 30 GHD/anchored sit-ups.","hero"],
  ["Tyler","RFT",["Pull-up bar","Barbell"],"5 rounds: 7 muscle-ups, 21 sumo deadlift high-pulls (95).","hero"],
  ["Garrett","RFT",["Bodyweight","Pull-up bar"],"3 rounds: 75 squats, 25 ring HSPU, 25 L-pull-ups.","hero"],
  ["War Frank","RFT",["Pull-up bar","Bodyweight"],"3 rounds: 25 muscle-ups, 100 squats, 35 GHD/anchored sit-ups.","hero"],
  ["Paul","RFT",["Jump rope","Pull-up bar","Barbell"],"5 rounds: 50 double-unders, 35 knees-to-elbow, 20-yd overhead walk (185).","hero"],
  ["Jerry","For Time",["Rower"],"1 mi run, 2 km row, 1 mi run. Pure engine.","hero"],
  ["Rankel","AMRAP",["Barbell","Kettlebell","Pull-up bar"],"20 min AMRAP: 6 deadlifts (225), 7 burpee pull-ups, 10 KB swings (70), 200 m run.","hero"],
  ["Bull","RFT",["Jump rope","Barbell","Pull-up bar"],"2 rounds: 200 double-unders, 50 OHS (135), 50 pull-ups, 1 mi run.","hero"],
  ["Severin","For Time",["Pull-up bar","Bodyweight"],"50 strict pull-ups, 100 push-ups, 5 km run. Vest (20) if able.","hero"],
  ["Helton","RFT",["Dumbbells","Bodyweight"],"3 rounds: 800 m run, 30 DB squat cleans (50), 30 burpees.","hero"],
  ["Jack","AMRAP",["Barbell","Kettlebell","Box"],"20 min AMRAP: 10 push press (115), 10 KB swings (53), 10 box jumps (24).","hero"],
  ["Forrest","RFT",["Pull-up bar","Bodyweight"],"3 rounds: 20 L-pull-ups, 30 toes-to-bar, 40 burpees, 800 m run.","hero"],
  ["Manion","RFT",["Barbell"],"7 rounds: 400 m run, 29 back squats (135).","hero"],
  ["Whitten","RFT",["Kettlebell","Box","Wall ball"],"5 rounds: 22 KB swings (53), 22 box jumps (24), 400 m run, 22 burpees, 22 wall balls (20).","hero"],
  ["Klepto","RFT",["Box","Barbell","Bodyweight"],"4 rounds: 27 box jumps (24), 20 burpees, 11 squat cleans (145).","hero"],
  ["Zimmerman","AMRAP",["Pull-up bar","Barbell","Bodyweight"],"25 min AMRAP: 11 chest-to-bar pull-ups, 2 deadlifts (315), 10 HSPU.","hero"],
  ["Erin","RFT",["Dumbbells","Pull-up bar"],"5 rounds: 15 DB split cleans (40 each), 21 pull-ups.","hero"],
  ["Mr Joshua","RFT",["Bodyweight","Barbell"],"5 rounds: 400 m run, 30 GHD/anchored sit-ups, 15 deadlifts (250).","hero"],
  ["Griff","For Time",["Bodyweight"],"800 m run, 400 m run backward, 800 m run, 400 m run backward.","hero"],
  ["Arnie","For Time",["Kettlebell"],"With one KB (53): 21 Turkish get-ups R, 50 swings, 21 OHS L, 50 swings, 21 OHS R, 50 swings, 21 TGU L.","hero"],

  // ============ OTHER / minimal-equipment / formats ============
  ["Fight Gone Bad","For Time",["Wall ball","Barbell","Box","Rower"],"3 rounds, 5 stations × 1 min: wall ball (20), SDHP (75), box jump (20), push press (75), row (cals). 1 min rest between rounds.","other"],
  ["Filthy Fifty","Chipper",["Box","Pull-up bar","Kettlebell","Wall ball","Jump rope"],"50 reps each: box jumps, jumping pull-ups, KB swings, walking lunges, knees-to-elbow, push press (45), back ext, wall balls, burpees, double-unders.","other"],
  ["Tabata This","Tabata",["Bodyweight","Rower","Pull-up bar"],"Tabata (20s on/10s off ×8) of row, squats, pull-ups, push-ups, sit-ups. Lowest round scores each.","other"],
  ["Cindy XXL","AMRAP",["Pull-up bar","Bodyweight"],"30 min Cindy: 5 pull-ups, 10 push-ups, 15 squats.","other"],
  ["DB Fran","For Time",["Dumbbells","Pull-up bar"],"21-15-9: dumbbell thrusters + pull-ups.","other"],
  ["DB EMOM","EMOM",["Dumbbells"],"20 min EMOM — odd: 10 DB snatches, even: 10 DB thrusters.","other"],
  ["DB Chipper","Chipper",["Dumbbells","Box"],"50 DB snatches, 40 box jumps, 30 DB thrusters, 20 burpees, 10 DB clusters.","other"],
  ["KB AMRAP","AMRAP",["Kettlebell"],"15 min AMRAP: 10 KB swings, 10 goblet squats, 10 push-ups.","other"],
  ["KB EMOM","EMOM",["Kettlebell"],"16 min EMOM — odd: 15 swings, even: 12 goblet squats.","other"],
  ["Death by Burpees","Interval",["Bodyweight"],"Min 1: 1 burpee, +1 each minute until you can't finish in the minute.","other"],
  ["100 Burpees","For Time",["Bodyweight"],"100 burpees for time. Steady pace beats sprinting.","other"],
  ["Tabata Squats","Tabata",["Bodyweight"],"8 rounds, 20s on / 10s off air squats. Count your lowest round.","other"],
  ["Tabata Mix","Tabata",["Bodyweight"],"4 movements × 8 rounds (20/10): squats, push-ups, mountain climbers, hollow rocks.","other"],
  ["Run Ladder","Ladder",["Bodyweight"],"200-400-800-400-200 m run; 1-2-3-2-1 rounds of a triplet between each.","other"],
  ["5K Run","For Time",["Bodyweight"],"5 km run for time. Negative-split it.","other"],
  ["Row Sprints","Interval",["Rower"],"8 × 250 m row, rest 1 min. Hold an even pace.","other"],
  ["Box Jump EMOM","EMOM",["Box"],"10 min EMOM: 10 box jumps each minute (step down).","other"],
  ["Slam Ball Chipper","Chipper",["Slam ball","Box"],"800 m run, 40 slam balls, 30 DB snatches, 20 box jumps, 800 m run.","other"],
  ["21-15-9 Couplet","For Time",["Bodyweight"],"Pick any two movements, 21-15-9 for time (e.g. thrusters + burpees).","other"],
  ["AMRAP 20","AMRAP",["Bodyweight"],"Build your own 20 min AMRAP from 3 movements you choose.","other"],
  ["EMOM 24","EMOM",["Bodyweight"],"24 min, rotate 3 movements each minute (8 rounds).","other"]
];
