/* Shared WOD library — used by both the WOD Finder (wods.html) and the
 * WOD picker on a WOD training day (workout.html). Add as many as you want;
 * everything filters/searches automatically. [name, format, equipment[], description] */
window.WODS = [
  ["Fran","For Time",["Barbell","Pull-up bar"],"21-15-9: thrusters (95) + pull-ups. Go unbroken if you can."],
  ["Helen","RFT",["Kettlebell","Pull-up bar"],"3 rounds: 400 m run, 21 KB swings, 12 pull-ups."],
  ["Grace","For Time",["Barbell"],"30 clean & jerks for time (135). Find a rhythm."],
  ["Isabel","For Time",["Barbell"],"30 snatches for time (135)."],
  ["Cindy","AMRAP",["Pull-up bar","Bodyweight"],"20 min AMRAP: 5 pull-ups, 10 push-ups, 15 air squats."],
  ["Mary","AMRAP",["Bodyweight"],"20 min AMRAP: 5 HSPU, 10 pistols, 15 pull-ups (scale freely)."],
  ["Annie","For Time",["Jump rope"],"50-40-30-20-10: double-unders + sit-ups."],
  ["Jackie","For Time",["Rower","Barbell","Pull-up bar"],"1000 m row, 50 thrusters (45), 30 pull-ups."],
  ["Diane","For Time",["Barbell"],"21-15-9: deadlift (225) + handstand push-ups (scale HSPU)."],
  ["Karen","For Time",["Wall ball"],"150 wall balls (20) for time. Pace the sets."],
  ["Nancy","RFT",["Barbell"],"5 rounds: 400 m run + 15 overhead squats (95)."],
  ["Barbara","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 pull-ups, 30 push-ups, 40 sit-ups, 50 squats, rest 3 min."],
  ["Angie","For Time",["Pull-up bar","Bodyweight"],"100 pull-ups, 100 push-ups, 100 sit-ups, 100 squats — in order."],
  ["Chelsea","EMOM",["Pull-up bar","Bodyweight"],"EMOM 30 min: 5 pull-ups, 10 push-ups, 15 squats."],
  ["Murph","For Time",["Pull-up bar","Bodyweight"],"1 mi run, 100 pull-ups, 200 push-ups, 300 squats, 1 mi run. Vest optional. Partition the middle."],
  ["DT","RFT",["Barbell"],"5 rounds: 12 deadlifts, 9 hang power cleans, 6 push jerks (155)."],
  ["The Chief","AMRAP",["Barbell","Bodyweight"],"5 cycles of 3 min AMRAP: 3 power cleans, 6 push-ups, 9 squats. 1 min rest between."],
  ["JT","For Time",["Bodyweight"],"21-15-9: handstand push-ups, ring dips, push-ups."],
  ["Cindy XXL","AMRAP",["Pull-up bar","Bodyweight"],"30 min Cindy: 5 pull-ups, 10 push-ups, 15 squats."],
  ["DB Fran","For Time",["Dumbbells","Pull-up bar"],"21-15-9: dumbbell thrusters + pull-ups."],
  ["DB EMOM","EMOM",["Dumbbells"],"20 min EMOM — odd: 10 DB snatches, even: 10 DB thrusters."],
  ["DB Chipper","Chipper",["Dumbbells","Box"],"50 DB snatches, 40 box jumps, 30 DB thrusters, 20 burpees, 10 DB clusters."],
  ["KB AMRAP","AMRAP",["Kettlebell"],"15 min AMRAP: 10 KB swings, 10 goblet squats, 10 push-ups."],
  ["KB EMOM","EMOM",["Kettlebell"],"16 min EMOM — odd: 15 swings, even: 12 goblet squats."],
  ["Death by Burpees","Interval",["Bodyweight"],"Min 1: 1 burpee, +1 each minute until you can't finish in the minute."],
  ["100 Burpees","For Time",["Bodyweight"],"100 burpees for time. Steady pace beats sprinting."],
  ["Tabata Squats","Tabata",["Bodyweight"],"8 rounds, 20s on / 10s off air squats. Count your lowest round."],
  ["Tabata Mix","Tabata",["Bodyweight"],"4 movements × 8 rounds (20/10): squats, push-ups, mountain climbers, hollow rocks."],
  ["Run Ladder","Ladder",["Bodyweight"],"200-400-800-400-200 m run; 1-2-3-2-1 rounds of a triplet between each."],
  ["5K Run","For Time",["Bodyweight"],"5 km run for time. Negative-split it."],
  ["Row Sprints","Interval",["Rower"],"8 × 250 m row, rest 1 min. Hold an even pace."],
  ["Box Jump EMOM","EMOM",["Box"],"10 min EMOM: 10 box jumps each minute (step down)."],
  ["Slam Ball Chipper","Chipper",["Slam ball","Box"],"800 m run, 40 slam balls, 30 DB snatches, 20 box jumps, 800 m run."],
  ["Fight Gone Bad","For Time",["Wall ball","Barbell","Box","Rower"],"3 rounds, 5 stations × 1 min: wall ball, SDHP, box jump, push press, row. 1 min rest."],
  ["Filthy Fifty","Chipper",["Box","Pull-up bar","Kettlebell","Wall ball","Jump rope"],"50 reps each: box jumps, jumping pull-ups, KB swings, lunges, knees-to-elbow, push press, back ext, wall balls, burpees, double-unders."],
  ["21-15-9 Couplet","For Time",["Bodyweight"],"Pick any two movements, 21-15-9 for time (e.g. thrusters + burpees)."],
  ["AMRAP 20","AMRAP",["Bodyweight"],"Build your own 20 min AMRAP from 3 movements you choose."],
  ["EMOM 24","EMOM",["Bodyweight"],"24 min, rotate 3 movements each minute (8 rounds)."]
];
